### PR TITLE
feat: add endpoint to generate code refactor suggestions

### PR DESCRIPTION
**Pull request by diivi**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Adds an endpoint to generate code refactor suggestions.

## Related Tickets & Documents
https://github.com/open-sauced/ai/pull/90

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
@diivi let me know when you're ready for a review

**Comment by diivi** [comment]
I had one doubt:

how do we format code here? I tried `npm run format` but that didn't prettify the code.

**Comment by brandonroberts** [comment]
@diivi we're using eslint to format code, but its not handling spacing well at the moment. Recommened formatting is 2 spaces in general. If you clean up that spacing and the run `npm run format` you should be good there. We may add a prettier config here in the future, but have to see how much it conflicts with the eslint rules

**Review by brandonroberts — APPROVED** [review]
LGTM

**Pull request merged**
