### PR TITLE
fix: use url module

### PR DESCRIPTION
**Pull request by mtfoley**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

README update and different require for endpoint config. Just reflects what I needed to do in order to get this running locally.

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by mtfoley** [comment]
@0-vortex I've been doing some other poking around and found that if I seed locally from what's in the open-sauced/actions/hot-supabase directory, I have to drop the repos/users foreign key constraint.

Also, when I do `supabase db reset` and the `seed.sql` file gets used, the data doesn't make it into the tables and I wonder if something similar is going on.

**Comment by 0-vortex** [comment]
> @0-vortex I've been doing some other poking around and found that if I seed locally from what's in the open-sauced/actions/hot-supabase directory, I have to drop the repos/users foreign key constraint.
> 
> 
> 
> Also, when I do `supabase db reset` and the `seed.sql` file gets used, the data doesn't make it into the tables and I wonder if something similar is going on.

are you running supabase locally? otherwise you are juggling between adjusting the dev or the prod db, both things which shouldn't do right now as the entire structure should sit in the backend rather than actions.

To figure out if the seeds are broken just run them manually in supabase ui 😁

**Comment by mtfoley** [comment]
Yeah, I'm running it locally. i saw the docker containers pull and spin up, and i saw the `supabase/seed.sql` file get used. however, in the studio, the tables are empty. i realize now, the shell script to download copies of the SQL files from the actions repo was unnecessary, but i still wonder if we should troubleshoot why that initial seed file didn't fill up the db locally.

**Comment by 0-vortex** [comment]
> Yeah, I'm running it locally. i saw the docker containers pull and spin up, and i saw the `supabase/seed.sql` file get used. however, in the studio, the tables are empty. i realize now, the shell script to download copies of the SQL files from the actions repo was unnecessary, but i still wonder if we should troubleshoot why that initial seed file didn't fill up the db locally.

Sorry for the late reply - the seed file is being executed via psql inside the docker containers, similarly to what we are doing in the seed.sh script, hence the errors are not visible unless you check the process logs after you sh into the containers.
You can check the error yourself simply by renaming seed.sql and running it locally as described above, however the most likely culprit is bad insert order, conflicting with relationships, running the individual seed files in the logical order would fix this (i normally seed it this way and then adjust script in actions, however we are partially divergent until backend is deployed fully)

**Comment by 0-vortex** [comment]
We are moving off of this system for seeding, will close this :D

**Pull request closed without merging**
